import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

@Schema({ timestamps: true })
export class Post extends Document {
  @Prop({ type: Types.ObjectId, ref: 'Club', required: true })
  clubId: Types.ObjectId;

  @Prop({ required: true })
  text: string;

  @Prop()
  imageUrl?: string;

  @Prop({ type: Types.ObjectId, ref: 'Utilisateur', required: true })
  authorId: Types.ObjectId; // president user

  @Prop({ type: [{ type: Types.ObjectId, ref: 'Utilisateur' }], default: [] })
  likes: Types.ObjectId[];

  @Prop({ type: [{ type: Types.ObjectId, ref: 'Utilisateur' }], default: [] })
  dislikes: Types.ObjectId[];

  @Prop({
    type: [{
      _id: { type: Types.ObjectId, auto: true },
      userId: { type: Types.ObjectId, ref: 'Utilisateur' },
      userName: String,
      userAvatar: String,
      content: String,
      createdAt: { type: Date, default: Date.now },
      reactions: [{
        userId: { type: Types.ObjectId, ref: 'Utilisateur' },
        emoji: String
      }],
      replies: [{
        _id: { type: Types.ObjectId, auto: true },
        userId: { type: Types.ObjectId, ref: 'Utilisateur' },
        userName: String,
        userAvatar: String,
        content: String,
        createdAt: { type: Date, default: Date.now }
      }]
    }],
    default: []
  })
  comments: {
    _id?: Types.ObjectId;
    userId: Types.ObjectId;
    userName: string;
    userAvatar?: string;
    content: string;
    createdAt: Date;
    reactions?: {
      userId: Types.ObjectId;
      emoji: string;
    }[];
    replies?: {
      _id?: Types.ObjectId;
      userId: Types.ObjectId;
      userName: string;
      userAvatar?: string;
      content: string;
      createdAt: Date;
    }[];
  }[];

  // Added for TypeScript awareness of timestamp fields generated by Mongoose
  @Prop()
  createdAt?: Date;

  @Prop()
  updatedAt?: Date;
}

export type PostDocument = Post & Document;
export const PostSchema = SchemaFactory.createForClass(Post);
